INSERT INTO public.produtos (nome, descricao, categoria, preco, estoque, ativo) VALUES
('Smart Lâmpada LED Wi-Fi', 'Lâmpada inteligente compatível com Alexa e Google Assistente.', 'Casa Inteligente', 89.90, 120, true),
('Fone de Ouvido Bluetooth TWS', 'Fone de ouvido sem fio com cancelamento de ruído e alta fidelidade.', 'Áudio', 199.00, 85, true),
('Teclado Mecânico Gamer RGB', 'Teclado com switches blue, retroiluminação RGB e layout ABNT2.', 'Periféricos', 349.90, 45, true),
('Mouse Sem Fio Ergonômico', 'Mouse óptico sem fio com design vertical para maior conforto.', 'Periféricos', 129.50, 90, true),
('Cadeira de Escritório Ergonômica', 'Cadeira com apoio lombar ajustável e braços 4D.', 'Mobiliário', 899.00, 20, true),
('Monitor Ultrawide 29"', 'Monitor com resolução 2560x1080 e taxa de atualização de 75Hz.', 'Monitores', 1499.90, 15, true),
('Garrafa Térmica Inox 1L', 'Mantém a temperatura de líquidos por até 12 horas.', 'Utensílios', 79.90, 200, true),
('Cafeteira Elétrica Programável', 'Cafeteira para até 30 xícaras com timer e filtro permanente.', 'Eletrodomésticos', 249.00, 50, true),
('Mochila para Notebook 15.6"', 'Mochila resistente à água com compartimento acolchoado.', 'Acessórios', 189.90, 110, true),
('Webcam Full HD 1080p', 'Webcam com microfone embutido para videoconferências.', 'Periféricos', 299.00, 60, true),
('HD Externo 1TB USB 3.0', 'Disco rígido portátil para backup e armazenamento de arquivos.', 'Armazenamento', 399.00, 75, true),
('Power Bank 20000mAh', 'Carregador portátil com 2 saídas USB e carregamento rápido.', 'Acessórios', 159.90, 150, true),
('Kit de Ferramentas 129 Peças', 'Maleta de ferramentas completa para reparos domésticos.', 'Ferramentas', 219.00, 40, true),
('Fita de LED RGB 5m com Controle', 'Fita de LED adesiva para decoração de ambientes.', 'Iluminação', 99.90, 180, true),
('Aspirador de Pó Robô', 'Robô aspirador com mapeamento inteligente e controle por app.', 'Eletrodomésticos', 1299.00, 25, true),
('Liquidificador Turbo 1200W', 'Liquidificador com 12 velocidades e copo de 3L.', 'Eletrodomésticos', 179.90, 65, true),
('Jogo de Panelas Antiaderente 5 Peças', 'Conjunto de panelas com revestimento cerâmico.', 'Utensílios', 299.90, 35, true),
('Air Fryer 4L Digital', 'Fritadeira elétrica sem óleo com painel digital.', 'Eletrodomésticos', 449.00, 55, true),
('Smartwatch com GPS', 'Relógio inteligente com monitoramento cardíaco e GPS integrado.', 'Wearables', 599.00, 48, true),
('Câmera de Segurança Wi-Fi 360°', 'Câmera IP com visão noturna e áudio bidirecional.', 'Segurança', 259.90, 70, true),
('Roteador Wi-Fi 6 Mesh', 'Sistema de rede mesh para cobertura total da casa.', 'Redes', 799.00, 30, true),
('Hub USB-C 7 em 1', 'Adaptador com saídas HDMI, USB 3.0, SD e Ethernet.', 'Acessórios', 229.00, 95, true),
('Suporte para Monitor Articulado', 'Suporte de mesa para monitores de até 32 polegadas.', 'Acessórios', 179.00, 80, true),
('Luminária de Mesa LED', 'Luminária com controle de intensidade e temperatura de cor.', 'Iluminação', 119.90, 130, true),
('Barbeador Elétrico 3D', 'Barbeador com lâminas flutuantes, à prova d''água.', 'Cuidados Pessoais', 199.90, 60, true),
('Escova de Dentes Elétrica Sônica', 'Escova com 5 modos de limpeza e timer integrado.', 'Cuidados Pessoais', 149.90, 70, true),
('Kindle Paperwhite 16GB', 'Leitor de livros digitais com tela de 6.8" e iluminação ajustável.', 'Leitores Digitais', 699.00, 40, true),
('Caixa de Som Bluetooth Portátil', 'Caixa de som à prova d''água com 12h de bateria.', 'Áudio', 299.00, 88, true),
('Balança Digital de Cozinha', 'Balança de precisão para até 10kg.', 'Utensílios', 49.90, 250, true),
('Tapete de Yoga 6mm', 'Tapete de TPE ecológico e antiderrapante.', 'Esportes', 89.90, 100, true);
