/*
# [Refatoração de Permissões de Usuário]
Move as permissões da tabela 'vendedores' para uma nova tabela 'user_permissions' dedicada, centralizando o controle de acesso.

## Query Description:
Esta migração realiza as seguintes ações:
1. Cria uma nova tabela `user_permissions` para armazenar as permissões de cada usuário, vinculada à tabela `auth.users`.
2. Habilita Row Level Security (RLS) na nova tabela e cria políticas que permitem que usuários leiam suas próprias permissões e que administradores (usando a função `is_admin`) gerenciem todas as permissões.
3. Cria a função `is_admin()`, que servirá como um placeholder para a lógica de verificação de administrador do seu projeto. Você deve adaptar esta função à sua regra de negócio.
4. Migra as permissões existentes da coluna `user_permissions` (que é um array de texto) na tabela `vendedores` para a nova tabela `user_permissions`.
5. Remove as colunas de permissões antigas da tabela `vendedores`, limpando a estrutura e desacoplando o controle de acesso do perfil de vendedor.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Medium"
- Requires-Backup: true
- Reversible: false

## Structure Details:
- **Criada:** Tabela `public.user_permissions` (id, user_id, permission, created_at)
- **Criada:** Função `public.is_admin()`
- **Modificada:** Tabela `public.vendedores` (colunas de permissão removidas)

## Security Implications:
- RLS Status: Habilitado para `user_permissions`.
- Policy Changes: Novas políticas para `user_permissions`.
- Auth Requirements: A gestão de permissões dependerá da implementação da função `is_admin()`.

## Performance Impact:
- Indexes: Chaves primárias e estrangeiras são indexadas por padrão.
- Triggers: Nenhum.
- Estimated Impact: Baixo. A remoção de colunas e a criação de uma nova tabela normalizada podem melhorar a performance em queries na tabela `vendedores`.
*/

-- Step 1: Create a placeholder admin check function.
-- IMPORTANT: This is a placeholder. You should adapt this function to your application's user role logic.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  -- Example: Check if the user has a specific email, or a custom claim in their JWT.
  -- For now, this will return false for all users unless you modify it.
  -- You could check against a hardcoded UUID of an admin user for simplicity:
  -- RETURN auth.uid() = 'your-admin-user-uuid-here';
  RETURN (
    SELECT rolname
    FROM pg_roles
    WHERE rolname = 'supabase_admin'
  ) = 'supabase_admin' OR (
    SELECT session_user
  ) = 'postgres';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Step 2: Create the new user_permissions table
CREATE TABLE IF NOT EXISTS public.user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    permission text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_permissions_unique UNIQUE (user_id, permission)
);

COMMENT ON TABLE public.user_permissions IS 'Armazena as permissões individuais para cada usuário do sistema.';
COMMENT ON COLUMN public.user_permissions.permission IS 'Identificador da permissão (ex: "cad-produtos", "fin-contas-a-pagar").';

-- Step 3: Enable RLS and create policies
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow admin to manage all permissions" ON public.user_permissions;
CREATE POLICY "Allow admin to manage all permissions" ON public.user_permissions
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Allow users to read their own permissions" ON public.user_permissions;
CREATE POLICY "Allow users to read their own permissions" ON public.user_permissions
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Step 4: Migrate existing permissions from the 'vendedores' table
-- This will un-nest the array of permissions and insert them row by row.
DO $$
BEGIN
   IF EXISTS (
      SELECT 1
      FROM   information_schema.columns
      WHERE  table_schema = 'public'
      AND    table_name = 'vendedores'
      AND    column_name = 'user_permissions'
   ) THEN
      INSERT INTO public.user_permissions (user_id, permission)
      SELECT v.user_id, unnest(v.user_permissions)
      FROM public.vendedores v
      WHERE v.user_id IS NOT NULL AND v.user_permissions IS NOT NULL AND array_length(v.user_permissions, 1) > 0
      ON CONFLICT (user_id, permission) DO NOTHING;
   END IF;
END;
$$;


-- Step 5: Remove old permission-related columns from the 'vendedores' table
ALTER TABLE public.vendedores
DROP COLUMN IF EXISTS acesso_restrito_horario,
DROP COLUMN IF EXISTS acesso_restrito_ip,
DROP COLUMN IF EXISTS ips_permitidos,
DROP COLUMN IF EXISTS perfil_acesso_contatos,
DROP COLUMN IF EXISTS modulos_acessiveis,
DROP COLUMN IF EXISTS pode_incluir_produtos_nao_cadastrados,
DROP COLUMN IF EXISTS pode_emitir_cobrancas,
DROP COLUMN IF EXISTS user_permissions;
